// Edit this file to change the channel schedule.
// Times are in IST (Asia/Kolkata). Videos inside each slot loop until the next slot begins.
window.CHANNEL_CONFIG = {
  channelName: "Curated Time TV",
  timeZone: "Asia/Kolkata",
  timeZoneOffsetMinutes: 330,

  schedule: [
    {
      start: "01:00",
      end: "05:00",
      label: "Lo-fi music",
      note: "Overnight focus music. If the music rule is later made global, replace this with quiet night ragas.",
      videos: [
        { title: "study with me [pomodoro] 3 hours of lofi focus music | Lofi Girl", id: "53gNFOqDFcE", durationSeconds: 10804 },
        { title: "1 A.M Study Session | Lofi Girl", id: "lTRiuFIWV54", durationSeconds: 3674 },
        { title: "In the Zone | Chillhop Music", id: "9M4jZuqdw04", durationSeconds: 7235 },
        { title: "Endless Sunday | Chillhop Music", id: "D_uLM5i0Z4c", durationSeconds: 7288 },
      ],
    },
    {
      start: "05:00",
      end: "06:00",
      label: "Shloka",
      videos: [
        { title: "25 Essential Morning Prayers | Strumm Spiritual", id: "SvDIYVvcMIY", durationSeconds: 5249 },
        { title: "Powerful Vedic Chants | Strumm Spiritual", id: "cDEEMxnZtaE", durationSeconds: 4604 },
        { title: "Vedic chanting Non Stop", id: "LvKVXNmOqGw", durationSeconds: 3642 },
        { title: "Top 10 Morning Stotram - M.S. Subbulakshmi", id: "TWMbwsFfnF8", durationSeconds: 5973 },
      ],
    },
    {
      start: "06:00",
      end: "08:00",
      label: "Motivation / Thought-provoking",
      videos: [
        { title: "No Fear - Rabindranath Tagore", id: "O2g_5LOGRPg", durationSeconds: 95 },
        { title: "The Man in the Arena - Teddy Roosevelt", id: "A311CnTjfos", durationSeconds: 169 },
        { title: "RAGE - Motivational Video", id: "w1JJ5actiUM", durationSeconds: 186 },
        { title: "Invincible - Motivational Video", id: "zIFVwF35Jb0", durationSeconds: 232 },
        { title: "Seneca: LIFE CHANGING Quotes", id: "GTge3vVwvOk", durationSeconds: 272 },
        { title: "BE UNSHAKEABLE - Stoic Quote Collection", id: "VCzK1x39iQM", durationSeconds: 771 },
        { title: "COURAGE - Motivational Speech", id: "XcAehvwamzY", durationSeconds: 266 },
        { title: "Aristotle - Life Changing Quotes", id: "3xBXGbvSeNw", durationSeconds: 234 },
        { title: "Greatest Warrior Quotes: Live With Valor", id: "Wyx-l1UWWtg", durationSeconds: 261 },
        { title: "Lao Tzu Life Changing Quotes", id: "yERHSEP_zBM", durationSeconds: 261 },
        { title: "Do schools kill creativity? | Sir Ken Robinson | TED", id: "iG9CE55wbtY", durationSeconds: 1203 },
        { title: "The puzzle of motivation | Dan Pink | TED", id: "rrkrvAUbU9Y", durationSeconds: 1117 },
        { title: "The surprising habits of original thinkers | Adam Grant | TED", id: "fxbCHn6gE3U", durationSeconds: 925 },
        { title: "The Danger of a Single Story | Chimamanda Ngozi Adichie | TED", id: "D9Ihs241zeg", durationSeconds: 1156 },
        { title: "Inside the Mind of a Master Procrastinator | Tim Urban | TED", id: "arj7oStGLkU", durationSeconds: 844 },
        { title: "What really matters at the end of life | BJ Miller | TED", id: "apbSsILLh28", durationSeconds: 1148 },
        { title: "The surprising science of happiness | Dan Gilbert | TED", id: "4q1dgn_C0AU", durationSeconds: 1280 },
      ],
    },
    {
      start: "08:00",
      end: "10:00",
      label: "BBC Earth / Travel",
      videos: [
        { title: "A Journey Across Our Planet | Planet Earth II | BBC Earth", id: "bj2t7yGA_0M", durationSeconds: 2580 },
        { title: "Planet Earth Through The Seasons | BBC Earth", id: "tVQ5H4RNirk", durationSeconds: 2152 },
        { title: "A Journey Across Africa | BBC Earth", id: "3-QqmQ_MIe4", durationSeconds: 2983 },
        { title: "An Adventure Through Africa in 4K | BBC Earth", id: "o50N3-OaGdM", durationSeconds: 3538 },
        { title: "Prague | Rick Steves' Europe", id: "BFKzX7u-3yg", durationSeconds: 1504 },
        { title: "Rick Steves Iceland", id: "7glld8yO3Xo", durationSeconds: 3379 },
      ],
    },
    {
      start: "10:00",
      end: "12:00",
      label: "Cartoon",
      videos: [
        { title: "Tom and Jerry Vol. 31 | Warner Classics", id: "mkPLXTXY2WY", durationSeconds: 2453 },
        { title: "Tom and Jerry 1950s Mega Episode | Warner Classics", id: "SAaUjt0N-tA", durationSeconds: 2705 },
        { title: "Tom and Jerry Vol. 30 | Warner Classics", id: "4CU8h5f8TYY", durationSeconds: 2122 },
        { title: "Tom and Jerry Vol. 29 | Warner Classics", id: "G1nPAY7FQb8", durationSeconds: 2601 },
        { title: "Tom and Jerry Vol. 28 | Warner Classics", id: "u3ElS1Z_7Q4", durationSeconds: 2412 },
        { title: "Tom and Jerry Vol. 27 | Warner Classics", id: "SfAqDL7H3SY", durationSeconds: 2127 },
        { title: "Tom and Jerry Vol. 26 | Warner Classics", id: "CGJdWxSbPe0", durationSeconds: 2464 },
        { title: "Tom and Jerry Vol. 25 | Warner Classics", id: "wurbT0lbQ8E", durationSeconds: 2455 },
        { title: "Tom and Jerry Vol. 24 | Warner Classics", id: "iIL8626KWaA", durationSeconds: 2520 },
        { title: "Tom and Jerry Vol. 22 | Warner Classics", id: "gEr8N_lP5Yg", durationSeconds: 2876 },
        { title: "Tom and Jerry Vol. 20 | Warner Classics", id: "Dsh2YhU2NLk", durationSeconds: 3145 },
        { title: "Tom and Jerry Vol. 21 | Warner Classics", id: "dCFGntdhfdc", durationSeconds: 3463 },
        { title: "Tom and Jerry Vol. 20 | Warner Classics", id: "LNAEv9t5HWI", durationSeconds: 3088 },
        { title: "Tom and Jerry Vol. 15 | Warner Classics", id: "yop3Ts3bK8o", durationSeconds: 3281 },
        { title: "Tom and Jerry Vol. 13 | Warner Classics", id: "1rgtggI3lGs", durationSeconds: 3025 },
        { title: "Tom and Jerry Vol. 11 | Warner Classics", id: "SCrznOueqcs", durationSeconds: 3308 },
        { title: "Tom and Jerry | Quiet Please! | Warner Classics", id: "Gkysb_8N9os", durationSeconds: 458 },
        { title: "Popeye: Big Bad Sinbad", id: "-x_n-XaqKu4", durationSeconds: 303 },
        { title: "Superman: Electric Earthquake", id: "EZosvpToVp8", durationSeconds: 523 },
        { title: "Looney Tunes - 3 Hours of Cartoon Chaos", id: "C9yE5VsdsrY", durationSeconds: 11103 },
      ],
    },
    {
      start: "12:00",
      end: "15:00",
      label: "Bengali classic movie / drama",
      note: "Old Bengali films and drama-style cinema, pre-1960 where possible; Satyajit Ray is the exception.",
      videos: [
        { title: "Teen Kanya - Samapti | Satyajit Ray", id: "5MjMK1dgb6E", durationSeconds: 4354 },
        { title: "Charulata | Satyajit Ray", id: "hvMSSBSCXns", durationSeconds: 7122 },
        { title: "Apur Sansar | Satyajit Ray", id: "06SpsEz8v-s", durationSeconds: 6244 },
        { title: "Devi | Satyajit Ray", id: "sHk0sw1SHkk", durationSeconds: 6312 },
        { title: "Pather Panchali | Satyajit Ray", id: "f2B7dpPFuiY", durationSeconds: 7386 },
        { title: "Aparajito | Satyajit Ray", id: "scgyxNLiAL8", durationSeconds: 6013 },
        { title: "Jalsaghar | Satyajit Ray", id: "R68McAH9Jc4", durationSeconds: 4568 },
        { title: "Sare Chuattar | Bengali film, 1953", id: "eIJICFUIjk4", durationSeconds: 6234 },
        { title: "Agni Pariksha | Bengali film, 1954", id: "wdFSfrrXFMc", durationSeconds: 8160 },
        { title: "Harano Sur | Bengali film, 1957", id: "FEsMLRFpGqw", durationSeconds: 8798 },
        { title: "Chaoa Paoa | Bengali film, 1959", id: "rk_8npSCDx4", durationSeconds: 7288 },
        { title: "Mukti | Bengali film, 1937", id: "zg4SlOohYsQ", durationSeconds: 6956 },
        { title: "Udayer Pathey | Bengali social drama, 1944", id: "krc5RUnt2Pw", durationSeconds: 6453 },
        { title: "Vidyasagar | Bengali biographical film, 1950", id: "yPBcedarsGU", durationSeconds: 7606 },
        { title: "Michael Madhusudan | Bengali biographical film, 1950", id: "3aygZ5wYMKg", durationSeconds: 7605 },
      ],
    },
    {
      start: "15:00",
      end: "18:00",
      label: "Science",
      videos: [
        { title: "This game theory problem will change the way you see the world", id: "mScpHTIi-kM", durationSeconds: 1639 },
        { title: "The Man Who Took LSD and Changed The World", id: "zaXKQ70q4KQ", durationSeconds: 2020 },
        { title: "How One Company Secretly Poisoned The Planet", id: "SC2eSujzrUY", durationSeconds: 3248 },
        { title: "How a Student's Question Saved This NYC Skyscraper", id: "Q56PMJbCFXQ", durationSeconds: 2019 },
        { title: "Can you really reach anyone in 6 steps?", id: "CYlon2tvywA", durationSeconds: 1997 },
        { title: "But what is a Fourier series?", id: "r6sGWTCMz2k", durationSeconds: 1487 },
        { title: "But what is a neural network?", id: "aircAruvnKk", durationSeconds: 1120 },
        { title: "Why is a sphere's surface area four times its shadow?", id: "GNcFjFmqEc8", durationSeconds: 951 },
        { title: "Taylor series", id: "3d6DsjIBzJ4", durationSeconds: 1340 },
        { title: "Attention in transformers, step-by-step", id: "eMlx5fFNoYc", durationSeconds: 1570 },
        { title: "How wiggling charges give rise to light", id: "aXRTczANuIs", durationSeconds: 1293 },
        { title: "The Brachistochrone, with Steven Strogatz", id: "Cld0p3a43fU", durationSeconds: 962 },
        { title: "What They Probably Don't Teach You About Rainbows At School", id: "24GfgNtnjXc", durationSeconds: 1631 },
        { title: "Chaos: The Science of the Butterfly Effect | Veritasium", id: "fDek6cYijxI", durationSeconds: 771 },
        { title: "The Most Misunderstood Concept in Physics | Veritasium", id: "DxL2HoqLbyA", durationSeconds: 1635 },
        { title: "Terence Tao on the cosmic distance ladder | 3Blue1Brown", id: "YdOXS_9_P4U", durationSeconds: 1713 },
        { title: "The magic of Fibonacci numbers | Arthur Benjamin | TED", id: "SjSHVDfXHQ4", durationSeconds: 385 },
      ],
    },
    {
      start: "18:00",
      end: "21:00",
      label: "Bengali classics / Hindustani classical",
      note: "Only pre-1960 Bengali classic song traditions and North Indian classical music.",
      videos: [
        { title: "Raag Yaman - Ustad Amir Khan", id: "toJnqAL_nZs", durationSeconds: 3284 },
        { title: "Bade Ghulam Ali Khan - Bhup - Tarana - 1954", id: "9NFgrneJHGY", durationSeconds: 626 },
        { title: "Bade Ghulam Ali Khan - Raag Manj Khamaj - 1949", id: "sUAhqXdPCoo", durationSeconds: 205 },
        { title: "Mishra Brothers Rajan & Sajan - Miya Ki Malhar", id: "ySaUOxo1esU", durationSeconds: 4511 },
        { title: "Aykdin Chine Nebe Taare - Kanan Debi, 1945", id: "bWr_hoSEczw", durationSeconds: 183 },
        { title: "Nayan Je Mor Baran Mane Na - Angurbala, 1932", id: "cr1QKmrDrWM", durationSeconds: 199 },
        { title: "Mor Ghumoghore Ele Manohar - Indubala, 1931", id: "n6Tp5W4HvI8", durationSeconds: 213 },
        { title: "Amar Chokh Bnedhe Bhober Khelay - Renuka Sengupta, 1932", id: "b6Y4MnZHMKE", durationSeconds: 176 },
        { title: "Gagana Bhusan Tumi - Dilip Kumar Roy, 1937", id: "n-kweVzyymY", durationSeconds: 199 },
        { title: "Dhono Dhanye Puspe Bhora - Dilip Kumar Roy, 12-inch 78 rpm", id: "2LhrNwyvVUY", durationSeconds: 240 },
        { title: "Ustad Amir Khan - early 78 rpm record, 1934", id: "7qWUCt2kpo4", durationSeconds: 198 },
        { title: "Ustad Amir Khan - Hamsadhwani, 1955", id: "MROu8xiG5Eo", durationSeconds: 741 },
        { title: "Ustad Bade Ghulam Ali Khan - Raga Desi & Bhairavi, early 1950s", id: "EXeXnKiKg78", durationSeconds: 2742 },
        { title: "Ustad Bade Ghulam Ali Khan - Bhairavi & Kafi, live 1956", id: "KuvQ8VhvuWA", durationSeconds: 1750 },
        { title: "Kesarbai Kerkar - Durga, 78 rpm 1936", id: "oiDKUR7GZA4", durationSeconds: 582 },
        { title: "Kesarbai Kerkar - Desh, 78 rpm 1936", id: "eZJL6cNIdd8", durationSeconds: 434 },
        { title: "Abdul Karim Khan - Bhairavi, shellac 78 rpm 1934", id: "vjCCLtclCP0", durationSeconds: 503 },
        { title: "Abdul Karim Khan - Patdeep, vintage 78 rpm 1936", id: "Xxe07zMbIpI", durationSeconds: 247 },
        { title: "Subinoy Roy - Tagore Songs, Rabindra Sangeet Vol. 1", id: "TrQpfuEA2qQ", durationSeconds: 3797 },
        { title: "Subinoy Roy - Evergreen Rabindra Sangeet", id: "AMo2GZ-IqGU", durationSeconds: 3824 },
        { title: "Subinoy Roy - Brahmo Sangeet and Rabindra Sangeet", id: "kS9PfZme6R0", durationSeconds: 3915 },
        { title: "Kanika Banerjee - Rabindra Sangeet Radio Show", id: "g3HHl5JkIh4", durationSeconds: 3628 },
        { title: "Kanika Banerjee - Tagore Duets, Amra Dujana", id: "1Uwpjo3B9tI", durationSeconds: 1606 },
        { title: "Subinoy Roy - Bahe Nirantara Ananta Anandadhara", id: "qq-eZvm7xfU", durationSeconds: 596 },
        { title: "Subinoy Roy - Amare Tumi Asesh Korechho", id: "Rc7JMmeGKJo", durationSeconds: 300 },
        { title: "Subinoy Roy - Eki Labonnye Purno Prane", id: "yuL3PGq_zXo", durationSeconds: 325 },
        { title: "Nissar Hussain Khan - Chhayanat, Malkauns and Jhinjhoti", id: "vot0oMRiXuI", durationSeconds: 1594 },
        { title: "Nissar Hussain Khan - Chhayanat", id: "KT2iztFBYGc", durationSeconds: 469 },
        { title: "Nissar Hussain Khan - Malkauns", id: "HZp8SeLxi_A", durationSeconds: 668 },
        { title: "Nissar Hussain Khan - Jhinjhoti Tarana", id: "J5qc13VcmhI", durationSeconds: 463 },
        { title: "Nissar Hussain Khan - Desi", id: "nIcOcQ-b1ds", durationSeconds: 889 },
        { title: "Nissar Hussain Khan - Des", id: "L8PsVEUe7PU", durationSeconds: 750 },
        { title: "Nissar Hussain Khan - Darbari", id: "_BY99hnosn0", durationSeconds: 554 },
        { title: "Nissar Hussain Khan - Darbari Alap", id: "PihX4VhlpIY", durationSeconds: 2701 },
        { title: "Nissar Hussain Khan - Bairagi Bhairav", id: "XO-rqe0gWr0", durationSeconds: 209 },
        { title: "Nissar Hussain Khan - Bhairavi Tarana", id: "1W5hbGdnPfU", durationSeconds: 198 },
        { title: "Nissar Hussain Khan - Lalit, AIR Recording", id: "w1OSk80WIfI", durationSeconds: 198 },
        { title: "Mogubai Kurdikar - Sohini and Punjabi", id: "02QYitnkxfw", durationSeconds: 880 },
        { title: "Mogubai Kurdikar - Sampurna Malkauns", id: "fOzpkELCP8U", durationSeconds: 1586 },
        { title: "Mogubai Kurdikar - Sampurna Malkauns, Extended", id: "ET4iyrHXcKg", durationSeconds: 1958 },
        { title: "Kesarbai Kerkar - Durga, Rare Test Pressing 1936", id: "PX8_QeyHNNk", durationSeconds: 586 },
        { title: "Kesarbai Kerkar - Durga, 1946", id: "Fxs41hY8JDw", durationSeconds: 269 },
        { title: "Kesarbai Kerkar - Nat Kamod, 1946", id: "YiFFwSV1W9g", durationSeconds: 257 },
        { title: "Kesarbai Kerkar - Jaunpuri, 1944", id: "ykGcZvR05hM", durationSeconds: 252 },
        { title: "Kesarbai Kerkar - Lalit, 1944", id: "4PFlqIYsdUQ", durationSeconds: 254 },
        { title: "Kesarbai Kerkar - Maru Bihag, 1945", id: "QhUw7MwmMH8", durationSeconds: 253 },
        { title: "Kesarbai Kerkar - Malkauns, 1945", id: "NlRNn-RwYrI", durationSeconds: 246 },
        { title: "Kesarbai Kerkar - Paraj, 1945", id: "H_vo0tMNjSo", durationSeconds: 251 },
        { title: "Kesarbai Kerkar - Nand, 1945", id: "iKi3bx9kl1M", durationSeconds: 286 },
        { title: "Kesarbai Kerkar - Kukubh Bilawal, 1949", id: "OpwQSv5R6HY", durationSeconds: 271 },
        { title: "Kesarbai Kerkar - Desi, 1949", id: "hk88tLm-9H8", durationSeconds: 276 },
        { title: "Kesarbai Kerkar - Bhairavi, 1955", id: "mFuFxVrC444", durationSeconds: 212 },
        { title: "Kesarbai Kerkar - Bibhas, 1955", id: "_N1QZ-LPxWo", durationSeconds: 207 },
        { title: "Rajan and Sajan Mishra - Raga Malkauns", id: "6fk_1SdD3SY", durationSeconds: 3032 },
        { title: "Rajan and Sajan Mishra - Raga Desi", id: "BAzm0gT4Yuw", durationSeconds: 3206 },
        { title: "Rajan and Sajan Mishra - Raga Tilak Kamod", id: "MfX1-MU6yzU", durationSeconds: 3183 },
        { title: "Rajan and Sajan Mishra - Raga Hamsadhwani", id: "7LnAh-2OcQM", durationSeconds: 3969 },
        { title: "Rajan and Sajan Mishra - Raga Lalit", id: "zC1rC50Pl3o", durationSeconds: 1785 },
        { title: "Rajan and Sajan Mishra - Raga Gorakh Kalyan", id: "mhDgit2rozA", durationSeconds: 1527 },
        { title: "Rajan and Sajan Mishra - Raga Bageshree, 1986", id: "qcnK4mUpNPQ", durationSeconds: 724 },
        { title: "Rajan and Sajan Mishra - Raga Jaijaiwanti", id: "esdoUvlAOGE", durationSeconds: 914 },
        { title: "Rajan and Sajan Mishra - Raga Durga, Akashvani Sangeet Sammelan 1982", id: "tDTCE_H-ufU", durationSeconds: 1542 },
        { title: "Ranadhir Roy - Esraj Raga Shuddh Sarang, Paris 1985", id: "s8EU51frobg", durationSeconds: 2765 },
        { title: "Ranadhir Roy - Esraj Raga Desh", id: "7k119A1Axtk", durationSeconds: 1270 },
        { title: "Ranadhir Roy - Esraj Raga Yaman", id: "HXiRxZzuoEo", durationSeconds: 2595 },
        { title: "Ranadhir Roy - Esraj Raga Shyam Kalyan", id: "yOHflIg1f40", durationSeconds: 3576 },
        { title: "Ranadhir Roy - Esraj Raga Jonpuri, Paris 1985", id: "fddwIeKPzvs", durationSeconds: 1801 },
        { title: "Veena Sahasrabuddhe - Raga Chhayanat", id: "nT9dKU45tdc", durationSeconds: 1788 },
        { title: "Veena Sahasrabuddhe - Raga Multani", id: "bv6Q9G9w0VA", durationSeconds: 1771 },
        { title: "Veena Sahasrabuddhe - Tarana, Flights of Melody", id: "6lqRWaGd8bc", durationSeconds: 3650 },
        { title: "Veena Sahasrabuddhe - Raga Durga", id: "mn9EntMOyUA", durationSeconds: 1702 },
        { title: "Veena Sahasrabuddhe - Raga Shankara", id: "V_mk_-rMU-Y", durationSeconds: 1748 },
        { title: "Veena Sahasrabuddhe - Raga Bhoop", id: "3LsXFmqStsw", durationSeconds: 3369 },
        { title: "Veena Sahasrabuddhe - Raga Bageshri", id: "ObFeG7PIO1Q", durationSeconds: 3070 },
        { title: "Veena Sahasrabuddhe - Raga Bihag", id: "j6DlmUaxnhQ", durationSeconds: 1791 },
        { title: "Veena Sahasrabuddhe - Raga Jog Kauns", id: "mUXJu4YjYkY", durationSeconds: 2279 },
        { title: "Veena Sahasrabuddhe - Raga Bilaskhani Todi", id: "7mVyv2gSbfI", durationSeconds: 1799 },
        { title: "Veena Sahasrabuddhe - Raga Ahir Bhairav and Tarana", id: "wM125Su0VgM", durationSeconds: 1851 },
        { title: "Veena Sahasrabuddhe - Raga Marwa", id: "tfZRBc4hfpQ", durationSeconds: 2190 },
        { title: "Veena Sahasrabuddhe - Raga Miyan Malhar", id: "A7uqGDJ_JTQ", durationSeconds: 3219 },
        { title: "Veena Sahasrabuddhe - Raga Jog", id: "2AGewbgftD8", durationSeconds: 1958 },
        { title: "Veena Sahasrabuddhe - Raga Darbari Kanada", id: "oF2hZcbBRlM", durationSeconds: 1804 },
        { title: "Veena Sahasrabuddhe - Miyan ki Todi and Miya ka Malhar", id: "aXhH7AlSKAc", durationSeconds: 3307 },
      ],
    },
    {
      start: "21:00",
      end: "22:00",
      label: "Health / Finance",
      videos: [
        { title: "The Dark Reality of World's Fattest Country", id: "kk8Z4XIT4Qs", durationSeconds: 1332 },
        { title: "What is Communism?", id: "4UJM4RFQjpU", durationSeconds: 1197 },
        { title: "What is Capitalism?", id: "Cf4uQg03jYg", durationSeconds: 1005 },
        { title: "Sleep Is Your Superpower | Matt Walker | TED", id: "5MuIMqhT8DM", durationSeconds: 1158 },
        { title: "Why Social Health Is Key to Happiness and Longevity | TED", id: "LpSDuDIaBGk", durationSeconds: 576 },
        { title: "The Fundamentals: Why is Investing Important? | The Plain Bagel", id: "I81xqr8HzBE", durationSeconds: 545 },
        { title: "The Difference Between Trading and Investing | The Plain Bagel", id: "dmqoqVwFopE", durationSeconds: 629 },
        { title: "Bonds vs. stocks | Khan Academy", id: "rs1md3e4aYU", durationSeconds: 561 },
      ],
    },
    {
      start: "22:00",
      end: "23:00",
      label: "Short film",
      videos: [
        { title: "Out Full SparkShort | Pixar", id: "OkLZN0ziLuI", durationSeconds: 633 },
        { title: "AFTER THE RAIN | Omeleto", id: "qEaoaRpRRzo", durationSeconds: 535 },
        { title: "1500 WORDS | Omeleto", id: "-waMtGtxAdg", durationSeconds: 526 },
        { title: "LOST AND FOUND | Omeleto", id: "VBps1IvCyj0", durationSeconds: 450 },
        { title: "EXIT STRATEGY | Omeleto", id: "68f27rqP_NY", durationSeconds: 909 },
        { title: "Panthar Mangsho | Ullas Mallick | Mirchi Bangla Audio Story", id: "w9esPNhfPhc", durationSeconds: 2174 },
        { title: "Inhaler | Koustav Samanta | Mirchi Bangla Audio Story", id: "J6MI6QknKGo", durationSeconds: 2012 },
        { title: "Satyajit Ray | Golpokothon by Kollol", id: "zMmaqJERNTY", durationSeconds: 2631 },
        { title: "The New Catacomb | Sir Arthur Conan Doyle | Radio Milan Audio Story", id: "PeIeBt_4IJI", durationSeconds: 1939 },
        { title: "Otithi | Rabindranath Tagore | Radio Milan Audio Story", id: "4VFp3jZk-XM", durationSeconds: 3344 },
      ],
    },
    {
      start: "23:00",
      end: "01:00",
      label: "Historical biography / speeches / audiobooks",
      videos: [
        { title: "Rabindranath Tagore - A Film by Satyajit Ray", id: "-VsiBNepmp0", durationSeconds: 3085 },
        { title: "Rabindranath Tagore's Own Voice & Video Footage", id: "EMN8_7C3lzc", durationSeconds: 369 },
        { title: "Sarojini Naidu Greeting Americans In 1928", id: "BlsZvuNhp4U", durationSeconds: 109 },
        { title: "Raja Ram Mohan Roy - The First Indian Liberal", id: "5HTK6XnX-ns", durationSeconds: 946 },
        { title: "How Hitler Brainwashed Millions of People", id: "laisVDBJ204", durationSeconds: 959 },
        { title: "Swami Vivekananda - How Naren became a Monk", id: "PA80BSo8XQQ", durationSeconds: 951 },
        { title: "Rabindranath Tagore - How a School Drop-Out Won the Nobel Prize", id: "HnpMTINOBHo", durationSeconds: 740 },
        { title: "Gandhi in 5 Minutes | British Pathe", id: "codWemzsW40", durationSeconds: 279 },
        { title: "The vision and philosophy of Gandhi | Prasar Bharati Archives", id: "0Etsy3LPddU", durationSeconds: 1713 },
        { title: "1963 - A Talk on Swami Vivekananda | Prasar Bharati Archives", id: "2indUgqt-KU", durationSeconds: 796 },
        { title: "Autobiography of a Yogi, Part 1/3 | LibriVox", id: "hbWzFlszaKM", durationSeconds: 25473 },
      ],
    },
  ],
};
