// Edit this file to change the channel schedule.
// Times follow each viewer's local browser clock.
// Videos inside each slot loop until the next slot begins.
window.CHANNEL_CONFIG = {
  channelName: "Curated Time TV",

  schedule: [
    {
      start: "01:00",
      end: "02:50:41",
      label: "Lo-fi music",
      buffer: true,
      note: "Overnight focus music. This is the flexible buffer block when another program needs a little extra time.",
      videos: [
        { title: "study with me [pomodoro] 3 hours of lofi focus music | Lofi Girl", id: "53gNFOqDFcE", durationSeconds: 10804 },
        { title: "1 A.M Study Session | Lofi Girl", id: "lTRiuFIWV54", durationSeconds: 3674 },
        { title: "In the Zone | Chillhop Music", id: "9M4jZuqdw04", durationSeconds: 7235 },
        { title: "Endless Sunday | Chillhop Music", id: "D_uLM5i0Z4c", durationSeconds: 7288 },
      ],
    },
    {
      start: "02:50:41",
      end: "06:00",
      label: "Buddhist chants / morning meditation",
      note: "Buddhist morning chants followed by the curator's requested closing meditation sequence.",
      videos: [
        { title: "Mantra of Avalokiteshvara - Full Length Version", id: "8DDc1UJqMWM", durationSeconds: 1435 },
        { title: "Greatest Buddha Music of All Time - Dharani and Buddhist Mantras", id: "ABy95341Dto", durationSeconds: 7310 },
        { title: "Sri Venkatesha Stotram - Invoking the Lord's Mercy", id: "_yhBlE3D9cc", durationSeconds: 330 },
        { title: "Vedic Chanting - Manish Vyas", id: "GePN4-Cajvk", durationSeconds: 275 },
        { title: "Guided Meditation - Manifest Your Dreams", id: "1VHmIdeoOmE", durationSeconds: 2009 },
      ],
    },
    {
      start: "06:00",
      end: "08:00",
      label: "Motivation / Thought-provoking",
      videos: [
        { title: "No Fear - Rabindranath Tagore", id: "O2g_5LOGRPg", durationSeconds: 95 },
        { title: "The Man in the Arena - Teddy Roosevelt", id: "A311CnTjfos", durationSeconds: 169 },
        { title: "RAGE - Motivational Video", id: "w1JJ5actiUM", durationSeconds: 186 },
        { title: "Invincible - Motivational Video", id: "zIFVwF35Jb0", durationSeconds: 232 },
        { title: "Seneca: LIFE CHANGING Quotes", id: "GTge3vVwvOk", durationSeconds: 272 },
        { title: "BE UNSHAKEABLE - Stoic Quote Collection", id: "VCzK1x39iQM", durationSeconds: 771 },
        { title: "COURAGE - Motivational Speech", id: "XcAehvwamzY", durationSeconds: 266 },
        { title: "Aristotle - Life Changing Quotes", id: "3xBXGbvSeNw", durationSeconds: 234 },
        { title: "Greatest Warrior Quotes: Live With Valor", id: "Wyx-l1UWWtg", durationSeconds: 261 },
        { title: "Lao Tzu Life Changing Quotes", id: "yERHSEP_zBM", durationSeconds: 261 },
        { title: "Do schools kill creativity? | Sir Ken Robinson | TED", id: "iG9CE55wbtY", durationSeconds: 1203 },
        { title: "The puzzle of motivation | Dan Pink | TED", id: "rrkrvAUbU9Y", durationSeconds: 1117 },
        { title: "The surprising habits of original thinkers | Adam Grant | TED", id: "fxbCHn6gE3U", durationSeconds: 925 },
        { title: "The Danger of a Single Story | Chimamanda Ngozi Adichie | TED", id: "D9Ihs241zeg", durationSeconds: 1156 },
        { title: "Inside the Mind of a Master Procrastinator | Tim Urban | TED", id: "arj7oStGLkU", durationSeconds: 844 },
        { title: "What really matters at the end of life | BJ Miller | TED", id: "apbSsILLh28", durationSeconds: 1148 },
        { title: "The surprising science of happiness | Dan Gilbert | TED", id: "4q1dgn_C0AU", durationSeconds: 1280 },
      ],
    },
    {
      start: "08:00",
      end: "10:00",
      label: "BBC Earth / Travel",
      videos: [
        { title: "A Journey Across Our Planet | Planet Earth II | BBC Earth", id: "bj2t7yGA_0M", durationSeconds: 2580 },
        { title: "Planet Earth Through The Seasons | BBC Earth", id: "tVQ5H4RNirk", durationSeconds: 2152 },
        { title: "A Journey Across Africa | BBC Earth", id: "3-QqmQ_MIe4", durationSeconds: 2983 },
        { title: "An Adventure Through Africa in 4K | BBC Earth", id: "o50N3-OaGdM", durationSeconds: 3538 },
        { title: "Prague | Rick Steves' Europe", id: "BFKzX7u-3yg", durationSeconds: 1504 },
        { title: "Rick Steves Iceland", id: "7glld8yO3Xo", durationSeconds: 3379 },
      ],
    },
    {
      start: "10:00",
      end: "12:00",
      label: "Cartoon",
      videos: [
        { title: "Tom and Jerry Vol. 31 | Warner Classics", id: "mkPLXTXY2WY", durationSeconds: 2453 },
        { title: "Tom and Jerry 1950s Mega Episode | Warner Classics", id: "SAaUjt0N-tA", durationSeconds: 2705 },
        { title: "Tom and Jerry Vol. 30 | Warner Classics", id: "4CU8h5f8TYY", durationSeconds: 2122 },
        { title: "Tom and Jerry Vol. 29 | Warner Classics", id: "G1nPAY7FQb8", durationSeconds: 2601 },
        { title: "Tom and Jerry Vol. 28 | Warner Classics", id: "u3ElS1Z_7Q4", durationSeconds: 2412 },
        { title: "Tom and Jerry Vol. 27 | Warner Classics", id: "SfAqDL7H3SY", durationSeconds: 2127 },
        { title: "Tom and Jerry Vol. 26 | Warner Classics", id: "CGJdWxSbPe0", durationSeconds: 2464 },
        { title: "Tom and Jerry Vol. 25 | Warner Classics", id: "wurbT0lbQ8E", durationSeconds: 2455 },
        { title: "Tom and Jerry Vol. 24 | Warner Classics", id: "iIL8626KWaA", durationSeconds: 2520 },
        { title: "Tom and Jerry Vol. 22 | Warner Classics", id: "gEr8N_lP5Yg", durationSeconds: 2876 },
        { title: "Tom and Jerry Vol. 20 | Warner Classics", id: "Dsh2YhU2NLk", durationSeconds: 3145 },
        { title: "Tom and Jerry Vol. 21 | Warner Classics", id: "dCFGntdhfdc", durationSeconds: 3463 },
        { title: "Tom and Jerry Vol. 20 | Warner Classics", id: "LNAEv9t5HWI", durationSeconds: 3088 },
        { title: "Tom and Jerry Vol. 15 | Warner Classics", id: "yop3Ts3bK8o", durationSeconds: 3281 },
        { title: "Tom and Jerry Vol. 13 | Warner Classics", id: "1rgtggI3lGs", durationSeconds: 3025 },
        { title: "Tom and Jerry Vol. 11 | Warner Classics", id: "SCrznOueqcs", durationSeconds: 3308 },
        { title: "Tom and Jerry | Quiet Please! | Warner Classics", id: "Gkysb_8N9os", durationSeconds: 458 },
        { title: "Popeye: Big Bad Sinbad", id: "-x_n-XaqKu4", durationSeconds: 303 },
        { title: "Superman: Electric Earthquake", id: "EZosvpToVp8", durationSeconds: 523 },
        { title: "Looney Tunes - 3 Hours of Cartoon Chaos", id: "C9yE5VsdsrY", durationSeconds: 11103 },
      ],
    },
    {
      start: "12:00",
      end: "15:00",
      label: "Bengali classic movie / drama",
      note: "Non-Ray entries are Bengali films before 1965; Satyajit Ray films are the standing exception.",
      videos: [
        { title: "Teen Kanya - Samapti | Satyajit Ray", id: "5MjMK1dgb6E", durationSeconds: 4354 },
        { title: "Charulata | Satyajit Ray", id: "hvMSSBSCXns", durationSeconds: 7122 },
        { title: "Apur Sansar | Satyajit Ray", id: "06SpsEz8v-s", durationSeconds: 6244 },
        { title: "Devi | Satyajit Ray", id: "sHk0sw1SHkk", durationSeconds: 6312 },
        { title: "Pather Panchali | Satyajit Ray", id: "f2B7dpPFuiY", durationSeconds: 7386 },
        { title: "Aparajito | Satyajit Ray", id: "scgyxNLiAL8", durationSeconds: 6013 },
        { title: "Jalsaghar | Satyajit Ray", id: "R68McAH9Jc4", durationSeconds: 4568 },
        { title: "Sare Chuattar | Uttam Kumar, 1953", id: "eIJICFUIjk4", durationSeconds: 6234 },
        { title: "Agni Pariksha | Uttam Kumar, 1954", id: "wdFSfrrXFMc", durationSeconds: 8160 },
        { title: "Harano Sur | Uttam Kumar, 1957", id: "FEsMLRFpGqw", durationSeconds: 8798 },
        { title: "Chaoa Paoa | Uttam Kumar, 1959", id: "rk_8npSCDx4", durationSeconds: 7288 },
        { title: "Mukti | Bengali film, 1937", id: "zg4SlOohYsQ", durationSeconds: 6956 },
        { title: "Udayer Pathey | Bengali social drama, 1944", id: "krc5RUnt2Pw", durationSeconds: 6453 },
        { title: "Vidyasagar | Bengali biographical film, 1950", id: "yPBcedarsGU", durationSeconds: 7606 },
        { title: "Michael Madhusudan | Bengali biographical film, 1950", id: "3aygZ5wYMKg", durationSeconds: 7605 },
        { title: "Teen Kanya - Postmaster | Satyajit Ray, 1961", id: "k0HnQZx89gs", durationSeconds: 2109 },
        { title: "Teen Kanya - Monihara | Satyajit Ray, 1961", id: "T2LbejQkHBk", durationSeconds: 3207 },
        { title: "Parash Pathar | Satyajit Ray, 1958", id: "tom5sP2JNzY", durationSeconds: 5625 },
        { title: "Kanchenjungha | Satyajit Ray, 1962", id: "sUj7cuiGP2w", durationSeconds: 5811 },
        { title: "Abhijan | Satyajit Ray, 1962", id: "h3YjnI7Oyy4", durationSeconds: 8173 },
        { title: "Mahanagar | Satyajit Ray, 1963", id: "OjhjDLeQNH8", durationSeconds: 8126 },
        { title: "Kapurush | Satyajit Ray, 1965", id: "Gcu0NYXyMGY", durationSeconds: 4155 },
        { title: "Mahapurush | Satyajit Ray, 1965", id: "joi6WSh3VG8", durationSeconds: 3982 },
        { title: "Nayak | Satyajit Ray, 1966", id: "LGfVvSzXhnk", durationSeconds: 7004 },
        { title: "Chiriakhana | Satyajit Ray, 1967", id: "VmLa-Ygwypw", durationSeconds: 7618 },
        { title: "Goopy Gyne Bagha Byne | Satyajit Ray, 1969", id: "sZPuVH0_X_Y", durationSeconds: 7299 },
        { title: "Aranyer Din Ratri | Satyajit Ray, 1970", id: "HcWVApMGq_E", durationSeconds: 6701 },
        { title: "Pratidwandi | Satyajit Ray, 1970", id: "enjp-LfY33s", durationSeconds: 6317 },
        { title: "Seemabaddha | Satyajit Ray, 1971", id: "bjfalVuJdso", durationSeconds: 6251 },
        { title: "Ashani Sanket | Satyajit Ray, 1973", id: "wqrUZwt49hk", durationSeconds: 5854 },
        { title: "Sonar Kella | Satyajit Ray, 1974", id: "aLhF9IemSYU", durationSeconds: 8196 },
        { title: "Jana Aranya | Satyajit Ray, 1976", id: "yh1atc3dLx0", durationSeconds: 7447 },
        { title: "Shatranj Ke Khilari | Satyajit Ray, 1977", id: "A3Fgm0yaWbA", durationSeconds: 6928 },
        { title: "Joi Baba Felunath | Satyajit Ray, 1979", id: "Gri1uKwUcXc", durationSeconds: 7220 },
        { title: "Hirak Rajar Deshe | Satyajit Ray, 1980", id: "5Da8ak63CU4", durationSeconds: 6649 },
        { title: "Sadgati | Satyajit Ray, 1981", id: "rRpaPV3QayY", durationSeconds: 2744 },
        { title: "Ghare Baire | Satyajit Ray, 1984", id: "zAxk-KRRie0", durationSeconds: 8304 },
        { title: "Ganashatru | Satyajit Ray, 1989", id: "Mfxkk0dPdkk", durationSeconds: 5979 },
        { title: "Shakha Proshakha | Satyajit Ray, 1990", id: "scekji9UvKg", durationSeconds: 7240 },
        { title: "Agantuk | Satyajit Ray, 1991", id: "JZ_HBguKPQg", durationSeconds: 7193 },
        { title: "Pikoo | Satyajit Ray, 1980", id: "QkaWHyJgM_E", durationSeconds: 1472 },
        { title: "Two | Satyajit Ray, 1964", id: "zACGLjd9JNY", durationSeconds: 723 },
        { title: "Saptapadi | Uttam Kumar, 1961", id: "el1hYsefgvM", durationSeconds: 8416 },
        { title: "Jhinder Bondi | Uttam Kumar, 1961", id: "7rFfNBDyhH8", durationSeconds: 6278 },
        { title: "Deya Neya | Uttam Kumar, 1963", id: "m1Q9wmOp-fM", durationSeconds: 7312 },
        { title: "Uttar Falguni | Bengali film, 1963", id: "CL_6NTkLvnI", durationSeconds: 7818 },
        { title: "Sesh Anka | Uttam Kumar, 1963", id: "yr-0z14pvec", durationSeconds: 7567 },
        { title: "Kancher Swarga | Bengali film, 1962", id: "42ghuCYElYI", durationSeconds: 8241 },
        { title: "Saat Pake Bandha | Bengali film, 1963", id: "lVfM367v8Hs", durationSeconds: 7679 },
        { title: "Bhranti Bilas | Uttam Kumar, 1963", id: "S_fhDVbex6k", durationSeconds: 5707 },
        { title: "Nisithe | Uttam Kumar, 1963", id: "BBOh6MKUM4A", durationSeconds: 7527 },
        { title: "Saharer Itikatha | Uttam Kumar, 1960", id: "gzyfwlrwH_A", durationSeconds: 6508 },
        { title: "Raja Saja | Uttam Kumar, 1960", id: "eq-ywl6qLOE", durationSeconds: 6891 },
        { title: "Marutirtha Hinglaj | Uttam Kumar, 1959", id: "lo_UmEwCmig", durationSeconds: 7157 },
        { title: "Kshudhita Pashan | Bengali film, 1960", id: "JBtzTBFkvkI", durationSeconds: 6134 },
        { title: "Sagarika | Uttam Kumar, 1956", id: "Z4wq155hVRE", durationSeconds: 6984 },
        { title: "Shilpi | Uttam Kumar, 1956", id: "abOPiKZ8j0g", durationSeconds: 7196 },
        { title: "Putra Badhu | Uttam Kumar, 1956", id: "M4ES2UMKdBs", durationSeconds: 8011 },
        { title: "Sadanander Mela | Uttam Kumar, 1954", id: "5PVPUFW417Q", durationSeconds: 6725 },
        { title: "Doctor | Bengali film, 1940", id: "QRnp8JtupHE", durationSeconds: 8247 },
        { title: "Chupi Chupi Ashey | Bengali film, 1960", id: "cdrmzezrdgQ", durationSeconds: 7156 },
        { title: "Abhoyer Biye | Uttam Kumar, 1957", id: "k9NnfXlx-0U", durationSeconds: 7710 },
        { title: "Surya Toran | Uttam Kumar, 1958", id: "ZHRYfdEUMT0", durationSeconds: 7982 },
        { title: "Saheb Bibi Golam | Uttam Kumar, 1956", id: "c_6TrejfklQ", durationSeconds: 9034 },
        { title: "Bicharak | Uttam Kumar, 1959", id: "HRXDzD--F1Y", durationSeconds: 7197 },
        { title: "Chhabi | Bengali film, 1959", id: "wvaoDD2I22A", durationSeconds: 5968 },
        { title: "Indrani | Uttam Kumar, 1958", id: "nMd4NTiVUxs", durationSeconds: 7314 },
        { title: "Maya Mriga | Uttam Kumar, 1960", id: "C4Soes9qzpc", durationSeconds: 8484 },
        { title: "Dui Bhai | Uttam Kumar, 1961", id: "ydktDHTcFUk", durationSeconds: 7256 },
        { title: "Dada Thakur | Bengali film, 1962", id: "xsyRoljriQk", durationSeconds: 8186 },
        { title: "Basu Paribar | Uttam Kumar, 1952", id: "OLPc5pgTvY8", durationSeconds: 6008 },
        { title: "Bou Thakuranir Haat | Uttam Kumar, 1953", id: "cDba-9tsprI", durationSeconds: 7523 },
        { title: "Moner Moyur | Uttam Kumar, 1954", id: "JoKVpZ0si4g", durationSeconds: 6179 },
        { title: "Ora Thakey Odhare | Uttam Kumar, 1954", id: "9ct0FjDO_h0", durationSeconds: 5625 },
        { title: "Champadangar Bou | Uttam Kumar, 1954", id: "CNb533FPjmQ", durationSeconds: 5238 },
        { title: "Maraner Pare | Uttam Kumar, 1954", id: "UPAESF-T5A8", durationSeconds: 7789 },
        { title: "Annapurnar Mandir | Uttam Kumar, 1954", id: "GPMu5XOhePQ", durationSeconds: 8157 },
        { title: "Grihapravesh | Uttam Kumar, 1954", id: "vQS0DE8cA-A", durationSeconds: 6185 },
        { title: "Mantrasakti | Uttam Kumar, 1954", id: "qTLuXxjFMtU", durationSeconds: 8156 },
        { title: "Sanjher Pradip | Uttam Kumar, 1955", id: "utNVqqDVY6U", durationSeconds: 6695 },
        { title: "Anupama | Uttam Kumar, 1955", id: "MT9Pd0IBics", durationSeconds: 7392 },
        { title: "Raikamal | Uttam Kumar, 1955", id: "H2IaFmH2rro", durationSeconds: 7279 },
        { title: "Debatra | Uttam Kumar, 1955", id: "_VANBwOcOx4", durationSeconds: 7483 },
        { title: "Shap Mochan | Uttam Kumar, 1955", id: "gRo8ZG3qTrE", durationSeconds: 10287 },
        { title: "Bidhilipi | Uttam Kumar, 1955", id: "UU-eR1rXJwY", durationSeconds: 6783 },
        { title: "Hrad | Uttam Kumar, 1955", id: "xIm8f0onN00", durationSeconds: 5785 },
        { title: "Kankabatir Ghat | Uttam Kumar, 1955", id: "0wfdrKcvq-w", durationSeconds: 8765 },
        { title: "Upahar | Uttam Kumar, 1955", id: "Cr-HnnilGMc", durationSeconds: 7318 },
        { title: "Bratacharini | Uttam Kumar, 1955", id: "36fG9O6B2_A", durationSeconds: 6685 },
        { title: "Sabar Oparey | Uttam Kumar, 1955", id: "9fkOaBv6utM", durationSeconds: 9018 },
        { title: "Laksha-Hira | Uttam Kumar, 1956", id: "KQCcR3oaOA4", durationSeconds: 7249 },
        { title: "Nabajanma | Uttam Kumar, 1956", id: "uEKq_sqU8nQ", durationSeconds: 7162 },
        { title: "Ekti Raat | Uttam Kumar, 1956", id: "Qyn_qhluAkE", durationSeconds: 8317 },
        { title: "Shyamali | Uttam Kumar, 1956", id: "C_cKfdWV0p4", durationSeconds: 7354 },
        { title: "Trijama | Uttam Kumar, 1956", id: "WfrosByZy4k", durationSeconds: 7122 },
        { title: "Prithivi Amarey Chai | Uttam Kumar, 1957", id: "QuJCn76Y-I4", durationSeconds: 9036 },
        { title: "Tasher Ghar | Uttam Kumar, 1957", id: "LImzj6SBbhg", durationSeconds: 9047 },
        { title: "Punarmilan | Uttam Kumar, 1957", id: "53XDp_mIv7o", durationSeconds: 5702 },
        { title: "Pathey Holo Deri | Uttam Kumar, 1957", id: "_yQ07sZsjBY", durationSeconds: 7579 },
        { title: "Jiban Trishna | Uttam Kumar, 1957", id: "gmo2sbpFMFM", durationSeconds: 7588 },
        { title: "Bandhu | Uttam Kumar, 1958", id: "DAjWUA_lb-Q", durationSeconds: 7400 },
        { title: "Rajlakshmi O Srikanta | Uttam Kumar, 1958", id: "1vWIuPdWln8", durationSeconds: 8514 },
        { title: "Pushpadhanu | Uttam Kumar, 1959", id: "ncQKewaiGZw", durationSeconds: 7582 },
        { title: "Gali Thekey Rajpat | Uttam Kumar, 1959", id: "yVYMzznD9pU", durationSeconds: 5438 },
        { title: "Khelaghar | Uttam Kumar, 1959", id: "S1lqrgkgkDs", durationSeconds: 7309 },
        { title: "Sonar Harin | Uttam Kumar, 1959", id: "Tjxpjm0WHDc", durationSeconds: 7504 },
        { title: "Abak Prithibi | Uttam Kumar, 1959", id: "oiCXW6RYKgA", durationSeconds: 5491 },
        { title: "Uttar Megh | Uttam Kumar, 1960", id: "8HYIuWgwQ6o", durationSeconds: 8183 },
        { title: "Hath Baralei Bondhu | Uttam Kumar, 1960", id: "t0EVGMJLMb8", durationSeconds: 7507 },
        { title: "Sakher Chor | Uttam Kumar, 1960", id: "lAQbmUsrZ0o", durationSeconds: 6942 },
        { title: "Suno Baranari | Uttam Kumar, 1960", id: "NloQ9zrRpFg", durationSeconds: 7307 },
        { title: "Sathi Hara | Uttam Kumar, 1961", id: "uJp3XN_oNY0", durationSeconds: 6677 },
        { title: "Agni Sanskar | Uttam Kumar, 1961", id: "_irJYBhKMVs", durationSeconds: 7102 },
        { title: "Bipasha | Uttam Kumar, 1962", id: "g3xiOMxbJzQ", durationSeconds: 7164 },
        { title: "Shiulibari | Uttam Kumar, 1962", id: "VHcO0SY0luE", durationSeconds: 7248 },
        { title: "Uttarayan | Uttam Kumar, 1963", id: "zy6xZeXbAvg", durationSeconds: 8945 },
        { title: "Surjasikha | Uttam Kumar, 1963", id: "MR3SiIM15vA", durationSeconds: 7911 },
        { title: "Bibhas | Uttam Kumar, 1964", id: "tVRjR-oerMQ", durationSeconds: 7667 },
        { title: "Jatugriha | Uttam Kumar, 1964", id: "eL0vw-owdXE", durationSeconds: 6392 },
        { title: "Natun Tirtha | Uttam Kumar, 1964", id: "9gAh2iyKlUs", durationSeconds: 7160 },
        { title: "Momer Alo | Uttam Kumar, 1964", id: "0Ad5Am93Gv0", durationSeconds: 6416 },
        { title: "Lalpathore | Uttam Kumar, 1964", id: "LsOWQomSZH0", durationSeconds: 7911 },
      ],
    },
    {
      start: "15:00",
      end: "18:00",
      label: "Science",
      videos: [
        { title: "This game theory problem will change the way you see the world", id: "mScpHTIi-kM", durationSeconds: 1639 },
        { title: "The Man Who Took LSD and Changed The World", id: "zaXKQ70q4KQ", durationSeconds: 2020 },
        { title: "How One Company Secretly Poisoned The Planet", id: "SC2eSujzrUY", durationSeconds: 3248 },
        { title: "How a Student's Question Saved This NYC Skyscraper", id: "Q56PMJbCFXQ", durationSeconds: 2019 },
        { title: "Can you really reach anyone in 6 steps?", id: "CYlon2tvywA", durationSeconds: 1997 },
        { title: "But what is a Fourier series?", id: "r6sGWTCMz2k", durationSeconds: 1487 },
        { title: "But what is a neural network?", id: "aircAruvnKk", durationSeconds: 1120 },
        { title: "Why is a sphere's surface area four times its shadow?", id: "GNcFjFmqEc8", durationSeconds: 951 },
        { title: "Taylor series", id: "3d6DsjIBzJ4", durationSeconds: 1340 },
        { title: "Attention in transformers, step-by-step", id: "eMlx5fFNoYc", durationSeconds: 1570 },
        { title: "How wiggling charges give rise to light", id: "aXRTczANuIs", durationSeconds: 1293 },
        { title: "The Brachistochrone, with Steven Strogatz", id: "Cld0p3a43fU", durationSeconds: 962 },
        { title: "What They Probably Don't Teach You About Rainbows At School", id: "24GfgNtnjXc", durationSeconds: 1631 },
        { title: "Chaos: The Science of the Butterfly Effect | Veritasium", id: "fDek6cYijxI", durationSeconds: 771 },
        { title: "The Most Misunderstood Concept in Physics | Veritasium", id: "DxL2HoqLbyA", durationSeconds: 1635 },
        { title: "Terence Tao on the cosmic distance ladder | 3Blue1Brown", id: "YdOXS_9_P4U", durationSeconds: 1713 },
        { title: "The magic of Fibonacci numbers | Arthur Benjamin | TED", id: "SjSHVDfXHQ4", durationSeconds: 385 },
      ],
    },
    {
      start: "18:00",
      end: "21:00",
      label: "Bengali classics / Hindustani classical",
      note: "Only pre-1960 Bengali classic song traditions and North Indian classical music.",
      videos: [
        { title: "Raag Yaman - Ustad Amir Khan", id: "toJnqAL_nZs", durationSeconds: 3284 },
        { title: "Bade Ghulam Ali Khan - Bhup - Tarana - 1954", id: "9NFgrneJHGY", durationSeconds: 626 },
        { title: "Bade Ghulam Ali Khan - Raag Manj Khamaj - 1949", id: "sUAhqXdPCoo", durationSeconds: 205 },
        { title: "Mishra Brothers Rajan & Sajan - Miya Ki Malhar", id: "ySaUOxo1esU", durationSeconds: 4511 },
        { title: "Aykdin Chine Nebe Taare - Kanan Debi, 1945", id: "bWr_hoSEczw", durationSeconds: 183 },
        { title: "Nayan Je Mor Baran Mane Na - Angurbala, 1932", id: "cr1QKmrDrWM", durationSeconds: 199 },
        { title: "Mor Ghumoghore Ele Manohar - Indubala, 1931", id: "n6Tp5W4HvI8", durationSeconds: 213 },
        { title: "Amar Chokh Bnedhe Bhober Khelay - Renuka Sengupta, 1932", id: "b6Y4MnZHMKE", durationSeconds: 176 },
        { title: "Gagana Bhusan Tumi - Dilip Kumar Roy, 1937", id: "n-kweVzyymY", durationSeconds: 199 },
        { title: "Dhono Dhanye Puspe Bhora - Dilip Kumar Roy, 12-inch 78 rpm", id: "2LhrNwyvVUY", durationSeconds: 240 },
        { title: "Ustad Amir Khan - early 78 rpm record, 1934", id: "7qWUCt2kpo4", durationSeconds: 198 },
        { title: "Ustad Amir Khan - Hamsadhwani, 1955", id: "MROu8xiG5Eo", durationSeconds: 741 },
        { title: "Ustad Bade Ghulam Ali Khan - Raga Desi & Bhairavi, early 1950s", id: "EXeXnKiKg78", durationSeconds: 2742 },
        { title: "Ustad Bade Ghulam Ali Khan - Bhairavi & Kafi, live 1956", id: "KuvQ8VhvuWA", durationSeconds: 1750 },
        { title: "Kesarbai Kerkar - Durga, 78 rpm 1936", id: "oiDKUR7GZA4", durationSeconds: 582 },
        { title: "Kesarbai Kerkar - Desh, 78 rpm 1936", id: "eZJL6cNIdd8", durationSeconds: 434 },
        { title: "Abdul Karim Khan - Bhairavi, shellac 78 rpm 1934", id: "vjCCLtclCP0", durationSeconds: 503 },
        { title: "Abdul Karim Khan - Patdeep, vintage 78 rpm 1936", id: "Xxe07zMbIpI", durationSeconds: 247 },
        { title: "Subinoy Roy - Tagore Songs, Rabindra Sangeet Vol. 1", id: "TrQpfuEA2qQ", durationSeconds: 3797 },
        { title: "Subinoy Roy - Evergreen Rabindra Sangeet", id: "AMo2GZ-IqGU", durationSeconds: 3824 },
        { title: "Subinoy Roy - Brahmo Sangeet and Rabindra Sangeet", id: "kS9PfZme6R0", durationSeconds: 3915 },
        { title: "Kanika Banerjee - Rabindra Sangeet Radio Show", id: "g3HHl5JkIh4", durationSeconds: 3628 },
        { title: "Kanika Banerjee - Tagore Duets, Amra Dujana", id: "1Uwpjo3B9tI", durationSeconds: 1606 },
        { title: "Subinoy Roy - Bahe Nirantara Ananta Anandadhara", id: "qq-eZvm7xfU", durationSeconds: 596 },
        { title: "Subinoy Roy - Amare Tumi Asesh Korechho", id: "Rc7JMmeGKJo", durationSeconds: 300 },
        { title: "Subinoy Roy - Eki Labonnye Purno Prane", id: "yuL3PGq_zXo", durationSeconds: 325 },
        { title: "Nissar Hussain Khan - Chhayanat, Malkauns and Jhinjhoti", id: "vot0oMRiXuI", durationSeconds: 1594 },
        { title: "Nissar Hussain Khan - Chhayanat", id: "KT2iztFBYGc", durationSeconds: 469 },
        { title: "Nissar Hussain Khan - Malkauns", id: "HZp8SeLxi_A", durationSeconds: 668 },
        { title: "Nissar Hussain Khan - Jhinjhoti Tarana", id: "J5qc13VcmhI", durationSeconds: 463 },
        { title: "Nissar Hussain Khan - Desi", id: "nIcOcQ-b1ds", durationSeconds: 889 },
        { title: "Nissar Hussain Khan - Des", id: "L8PsVEUe7PU", durationSeconds: 750 },
        { title: "Nissar Hussain Khan - Darbari", id: "_BY99hnosn0", durationSeconds: 554 },
        { title: "Nissar Hussain Khan - Darbari Alap", id: "PihX4VhlpIY", durationSeconds: 2701 },
        { title: "Nissar Hussain Khan - Bairagi Bhairav", id: "XO-rqe0gWr0", durationSeconds: 209 },
        { title: "Nissar Hussain Khan - Bhairavi Tarana", id: "1W5hbGdnPfU", durationSeconds: 198 },
        { title: "Nissar Hussain Khan - Lalit, AIR Recording", id: "w1OSk80WIfI", durationSeconds: 198 },
        { title: "Mogubai Kurdikar - Sohini and Punjabi", id: "02QYitnkxfw", durationSeconds: 880 },
        { title: "Mogubai Kurdikar - Sampurna Malkauns", id: "fOzpkELCP8U", durationSeconds: 1586 },
        { title: "Mogubai Kurdikar - Sampurna Malkauns, Extended", id: "ET4iyrHXcKg", durationSeconds: 1958 },
        { title: "Kesarbai Kerkar - Durga, Rare Test Pressing 1936", id: "PX8_QeyHNNk", durationSeconds: 586 },
        { title: "Kesarbai Kerkar - Durga, 1946", id: "Fxs41hY8JDw", durationSeconds: 269 },
        { title: "Kesarbai Kerkar - Nat Kamod, 1946", id: "YiFFwSV1W9g", durationSeconds: 257 },
        { title: "Kesarbai Kerkar - Jaunpuri, 1944", id: "ykGcZvR05hM", durationSeconds: 252 },
        { title: "Kesarbai Kerkar - Lalit, 1944", id: "4PFlqIYsdUQ", durationSeconds: 254 },
        { title: "Kesarbai Kerkar - Maru Bihag, 1945", id: "QhUw7MwmMH8", durationSeconds: 253 },
        { title: "Kesarbai Kerkar - Malkauns, 1945", id: "NlRNn-RwYrI", durationSeconds: 246 },
        { title: "Kesarbai Kerkar - Paraj, 1945", id: "H_vo0tMNjSo", durationSeconds: 251 },
        { title: "Kesarbai Kerkar - Nand, 1945", id: "iKi3bx9kl1M", durationSeconds: 286 },
        { title: "Kesarbai Kerkar - Kukubh Bilawal, 1949", id: "OpwQSv5R6HY", durationSeconds: 271 },
        { title: "Kesarbai Kerkar - Desi, 1949", id: "hk88tLm-9H8", durationSeconds: 276 },
        { title: "Kesarbai Kerkar - Bhairavi, 1955", id: "mFuFxVrC444", durationSeconds: 212 },
        { title: "Kesarbai Kerkar - Bibhas, 1955", id: "_N1QZ-LPxWo", durationSeconds: 207 },
        { title: "Rajan and Sajan Mishra - Raga Malkauns", id: "6fk_1SdD3SY", durationSeconds: 3032 },
        { title: "Rajan and Sajan Mishra - Raga Desi", id: "BAzm0gT4Yuw", durationSeconds: 3206 },
        { title: "Rajan and Sajan Mishra - Raga Tilak Kamod", id: "MfX1-MU6yzU", durationSeconds: 3183 },
        { title: "Rajan and Sajan Mishra - Raga Hamsadhwani", id: "7LnAh-2OcQM", durationSeconds: 3969 },
        { title: "Rajan and Sajan Mishra - Raga Lalit", id: "zC1rC50Pl3o", durationSeconds: 1785 },
        { title: "Rajan and Sajan Mishra - Raga Gorakh Kalyan", id: "mhDgit2rozA", durationSeconds: 1527 },
        { title: "Rajan and Sajan Mishra - Raga Bageshree, 1986", id: "qcnK4mUpNPQ", durationSeconds: 724 },
        { title: "Rajan and Sajan Mishra - Raga Jaijaiwanti", id: "esdoUvlAOGE", durationSeconds: 914 },
        { title: "Rajan and Sajan Mishra - Raga Durga, Akashvani Sangeet Sammelan 1982", id: "tDTCE_H-ufU", durationSeconds: 1542 },
        { title: "Ranadhir Roy - Esraj Raga Shuddh Sarang, Paris 1985", id: "s8EU51frobg", durationSeconds: 2765 },
        { title: "Ranadhir Roy - Esraj Raga Desh", id: "7k119A1Axtk", durationSeconds: 1270 },
        { title: "Ranadhir Roy - Esraj Raga Yaman", id: "HXiRxZzuoEo", durationSeconds: 2595 },
        { title: "Ranadhir Roy - Esraj Raga Shyam Kalyan", id: "yOHflIg1f40", durationSeconds: 3576 },
        { title: "Ranadhir Roy - Esraj Raga Jonpuri, Paris 1985", id: "fddwIeKPzvs", durationSeconds: 1801 },
        { title: "Veena Sahasrabuddhe - Raga Chhayanat", id: "nT9dKU45tdc", durationSeconds: 1788 },
        { title: "Veena Sahasrabuddhe - Raga Multani", id: "bv6Q9G9w0VA", durationSeconds: 1771 },
        { title: "Veena Sahasrabuddhe - Tarana, Flights of Melody", id: "6lqRWaGd8bc", durationSeconds: 3650 },
        { title: "Veena Sahasrabuddhe - Raga Durga", id: "mn9EntMOyUA", durationSeconds: 1702 },
        { title: "Veena Sahasrabuddhe - Raga Shankara", id: "V_mk_-rMU-Y", durationSeconds: 1748 },
        { title: "Veena Sahasrabuddhe - Raga Bhoop", id: "3LsXFmqStsw", durationSeconds: 3369 },
        { title: "Veena Sahasrabuddhe - Raga Bageshri", id: "ObFeG7PIO1Q", durationSeconds: 3070 },
        { title: "Veena Sahasrabuddhe - Raga Bihag", id: "j6DlmUaxnhQ", durationSeconds: 1791 },
        { title: "Veena Sahasrabuddhe - Raga Jog Kauns", id: "mUXJu4YjYkY", durationSeconds: 2279 },
        { title: "Veena Sahasrabuddhe - Raga Bilaskhani Todi", id: "7mVyv2gSbfI", durationSeconds: 1799 },
        { title: "Veena Sahasrabuddhe - Raga Ahir Bhairav and Tarana", id: "wM125Su0VgM", durationSeconds: 1851 },
        { title: "Veena Sahasrabuddhe - Raga Marwa", id: "tfZRBc4hfpQ", durationSeconds: 2190 },
        { title: "Veena Sahasrabuddhe - Raga Miyan Malhar", id: "A7uqGDJ_JTQ", durationSeconds: 3219 },
        { title: "Veena Sahasrabuddhe - Raga Jog", id: "2AGewbgftD8", durationSeconds: 1958 },
        { title: "Veena Sahasrabuddhe - Raga Darbari Kanada", id: "oF2hZcbBRlM", durationSeconds: 1804 },
        { title: "Veena Sahasrabuddhe - Miyan ki Todi and Miya ka Malhar", id: "aXhH7AlSKAc", durationSeconds: 3307 },
        { title: "Rajan and Sajan Mishra - Varanasi Performance", id: "XWQ3kfBLn54", durationSeconds: 502 },
        { title: "Rajan and Sajan Mishra - Raga Shree", id: "73pob960CtU", durationSeconds: 3446 },
        { title: "Rajan and Sajan Mishra - Raga Durga and Nand", id: "p6OzX7vkqpc", durationSeconds: 6704 },
        { title: "Rajan and Sajan Mishra - Raga Gorakh Kalyan and Rageshree", id: "LJfn82ysxzc", durationSeconds: 5643 },
        { title: "Rajan and Sajan Mishra - Suprabhat Classical Episode", id: "NMiGxZ03Saw", durationSeconds: 1379 },
        { title: "Rajan and Sajan Mishra - Bhajan in Raga Lalit Bhatiyar", id: "q5W1QNwriVQ", durationSeconds: 220 },
        { title: "Rajan and Sajan Mishra - Raga Nand", id: "EnwbPy4ISIo", durationSeconds: 133 },
        { title: "Rajan and Sajan Mishra - Chaturlal Memorial Festival", id: "6GLmbIrMImU", durationSeconds: 1544 },
        { title: "Rajan and Sajan Mishra - Full Length Magical Performance", id: "pGdwlPh8RwE", durationSeconds: 3280 },
        { title: "Rajan and Sajan Mishra - Live in Stuttgart", id: "yBSnCX19_q8", durationSeconds: 4669 },
        { title: "Rajan and Sajan Mishra - Raga Yaman, Part 2", id: "qwPU7DyrUBg", durationSeconds: 1578 },
        { title: "Rajan and Sajan Mishra - Raga Durga, Part 4", id: "_hos-__V7GA", durationSeconds: 540 },
        { title: "Veena Sahasrabuddhe - Raga Puriya Dhanashree, Tampa 2003", id: "CWoi5P897Mo", durationSeconds: 2862 },
        { title: "Veena Sahasrabuddhe - Raga Shuddh Sarang with Meera and Kabir Bhajans", id: "8W3jFs8rxXA", durationSeconds: 2456 },
        { title: "Veena Sahasrabuddhe - Raga Madhukauns", id: "1wMW9J7x3Kk", durationSeconds: 1808 },
        { title: "Veena Sahasrabuddhe - Raga Hamsadhwani", id: "ublrke2zeN4", durationSeconds: 1345 },
        { title: "Veena Sahasrabuddhe - Raga Shree", id: "yVMOTKkkbBU", durationSeconds: 1431 },
        { title: "Veena Sahasrabuddhe - Tarana in Raga Hameer", id: "ox1KyHEm_Zc", durationSeconds: 273 },
        { title: "Veena Sahasrabuddhe - Raga Megh Malhar", id: "SDcYFwFWTCc", durationSeconds: 1495 },
        { title: "Veena Sahasrabuddhe - Raga Hemant", id: "4tV4Y56wQlE", durationSeconds: 1672 },
        { title: "Veena Sahasrabuddhe - Ragas Basant, Des and Shuddh Sarang", id: "tTSiRBVFtjw", durationSeconds: 3647 },
        { title: "Veena Sahasrabuddhe - Raga Deshkar Tarana", id: "5ETbhJKjPFU", durationSeconds: 576 },
        { title: "Veena Sahasrabuddhe - Raga Abhogi", id: "b21NWM6otKM", durationSeconds: 1825 },
        { title: "Veena Sahasrabuddhe - Raga Kamod Alap and Tarana", id: "Tq7wtQEBYfM", durationSeconds: 602 },
        { title: "Veena Sahasrabuddhe - Raga Adana", id: "B4w6ZlhWVIs", durationSeconds: 571 },
        { title: "Veena Sahasrabuddhe - Raga Komal Rishabh Asavari", id: "sty31GWgOYU", durationSeconds: 1776 },
        { title: "Veena Sahasrabuddhe - Raga Gavathi", id: "AjHzJOwl2kY", durationSeconds: 1399 },
        { title: "Veena Sahasrabuddhe - Raga Des", id: "gFlBhKaC2VI", durationSeconds: 626 },
        { title: "Veena Sahasrabuddhe - Raga Dhani", id: "VzoKlWVcGIg", durationSeconds: 1390 },
        { title: "Veena Sahasrabuddhe - Raga Vibhas Live", id: "6u4fkBe28sw", durationSeconds: 2782 },
        { title: "Veena Sahasrabuddhe - Raga Bairagi", id: "dGD69-opXAk", durationSeconds: 1287 },
        { title: "Veena Sahasrabuddhe - Raga Hamir", id: "3TfXZnkAL8g", durationSeconds: 2491 },
        { title: "Veena Sahasrabuddhe - Bageshree and Jog, Sangeet Sammelan", id: "bGzlaB5m8Qk", durationSeconds: 4609 },
        { title: "Veena Sahasrabuddhe - Raga Bhupal Todi", id: "dQBTrtP7etk", durationSeconds: 2874 },
        { title: "Veena Sahasrabuddhe - Raga Miyan ki Todi", id: "0Zzo9Hvzkkg", durationSeconds: 1762 },
        { title: "Veena Sahasrabuddhe - Raga Gorakh Kalyan", id: "ArgJkVrgtrM", durationSeconds: 3776 },
        { title: "Veena Sahasrabuddhe - Raga Shuddha Sarang", id: "CIuGR4w3dI8", durationSeconds: 764 },
        { title: "Veena Sahasrabuddhe - Raga Sawani", id: "nE5jR6-Ba4U", durationSeconds: 1676 },
        { title: "Veena Sahasrabuddhe - Live Performance", id: "k3rLi9__xaw", durationSeconds: 4312 },
        { title: "Veena Sahasrabuddhe - Live Concert", id: "k-DiIuUOmM8", durationSeconds: 5609 },
        { title: "Veena Sahasrabuddhe - Live Performance", id: "8SAJjKULz7Y", durationSeconds: 3078 },
        { title: "Veena Sahasrabuddhe - Live Performance", id: "rHWxqa06I4U", durationSeconds: 4540 },
        { title: "Veena Sahasrabuddhe - Live Performance", id: "OSO0E9m-6hE", durationSeconds: 3428 },
        { title: "Veena Sahasrabuddhe - Live Concert", id: "aTNsaaBfB5I", durationSeconds: 4748 },
        { title: "Veena Sahasrabuddhe - Live Performance", id: "8tVg51ArRfs", durationSeconds: 4308 },
        { title: "Veena Sahasrabuddhe - Live Performance", id: "Rw6ALH__qDs", durationSeconds: 5015 },
        { title: "Veena Sahasrabuddhe - Ragas Maru Bihag and Basant", id: "suPgeadd31Q", durationSeconds: 4718 },
        { title: "Veena Sahasrabuddhe - Raga Gawati and Puriya Dhanashree", id: "SzyHFEMNBo8", durationSeconds: 3921 },
        { title: "Veena Sahasrabuddhe - Raga Marwa", id: "I0nyfvtHCuI", durationSeconds: 2190 },
        { title: "Veena Sahasrabuddhe - Raga Maru Bihag", id: "4g4BOKQmADg", durationSeconds: 1507 },
        { title: "Veena Sahasrabuddhe - Raga Madhukauns", id: "kfGuf0lmMzU", durationSeconds: 3409 },
        { title: "Veena Sahasrabuddhe - Raga Bageshri", id: "kHUkk4R3nHQ", durationSeconds: 1686 },
        { title: "Veena Sahasrabuddhe - Raga Vasant", id: "61BYn5WvyAw", durationSeconds: 1359 },
        { title: "Veena Sahasrabuddhe - Raga Miya ki Todi", id: "q4qe0mrxlT4", durationSeconds: 1631 },
        { title: "Veena Sahasrabuddhe - Raga Miya ki Malhar", id: "eDD3BhuXuNA", durationSeconds: 1676 },
        { title: "Veena Sahasrabuddhe - Raga Madhukauns with Bhajans", id: "-p4A_k3pS0w", durationSeconds: 4702 },
        { title: "Veena Sahasrabuddhe - Raga Shyam Kalyan", id: "fTDQ434PR1I", durationSeconds: 646 },
        { title: "Veena Sahasrabuddhe - Raga Shree", id: "dPJFy2kCS_0", durationSeconds: 1271 },
        { title: "Veena Sahasrabuddhe - Raga Patdeep", id: "n_s8h8EUGGI", durationSeconds: 806 },
        { title: "Veena Sahasrabuddhe - Raga Bageshree", id: "f6-XVJmexe4", durationSeconds: 1686 },
        { title: "Veena Sahasrabuddhe - Raga Jogkauns", id: "VwqvYNImwf8", durationSeconds: 2477 },
        { title: "Veena Sahasrabuddhe - Raga Rageshree", id: "x9scOm1iGTU", durationSeconds: 4213 },
        { title: "Veena Sahasrabuddhe - Raga Jogkauns", id: "r8jg_l83tJE", durationSeconds: 2643 },
        { title: "Veena Sahasrabuddhe - Raga Hansdhwani", id: "81rfmr9ODjs", durationSeconds: 1420 },
        { title: "Veena Sahasrabuddhe - Raga Vrindavani Sarang", id: "mxNQaak18Oc", durationSeconds: 3220 },
        { title: "Veena Sahasrabuddhe - Raga Lalita Gauri", id: "vx2wLc3MAOw", durationSeconds: 2155 },
        { title: "Veena Sahasrabuddhe - Bandish Vol. 1", id: "VLnGfKu-9L4", durationSeconds: 3575 },
        { title: "Veena Sahasrabuddhe - Raga Malkauns", id: "E4BcDEtcAos", durationSeconds: 2689 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "xHu0H3Z856I", durationSeconds: 7618 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "EXvlVHM8ju0", durationSeconds: 9804 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "HaQjz7CFloQ", durationSeconds: 5145 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "2KhfMLqdUgo", durationSeconds: 3422 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "cQXgk8CiEbM", durationSeconds: 4929 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "h3gWqYd--hk", durationSeconds: 4283 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "Ef0e0kzvj3g", durationSeconds: 9804 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "EnSgOeQ5LSU", durationSeconds: 12003 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "vEv5P2dwNQI", durationSeconds: 9249 },
        { title: "Veena Sahasrabuddhe - Concert Recording", id: "80mxV1ts51c", durationSeconds: 4605 },
        { title: "Veena Sahasrabuddhe - Madhukar Aaj Basant", id: "L7-iw3353ig", durationSeconds: 520 },
        { title: "Veena Sahasrabuddhe - Nirgun Awadhoota Gagan Ghata", id: "FDUZ8IfSUo8", durationSeconds: 385 },
        { title: "Veena Sahasrabuddhe - Mhari Sudh Budh", id: "2oRCKZbxJlg", durationSeconds: 459 },
        { title: "Veena Sahasrabuddhe - Bhajans", id: "Hb0v5cpdpec", durationSeconds: 1771 },
        { title: "Veena Sahasrabuddhe - Bhajan Naam", id: "oMeA_lOHlOo", durationSeconds: 493 },
        { title: "Veena Sahasrabuddhe - Bhajan Guruji", id: "bCxlHiQny78", durationSeconds: 800 },
        { title: "Veena Sahasrabuddhe - Bhajan", id: "IHfn3XxcgCw", durationSeconds: 571 },
        { title: "Veena Sahasrabuddhe - Bhajan", id: "jFxznGRmZn8", durationSeconds: 800 },
        { title: "Veena Sahasrabuddhe - Bhajan", id: "MP4aVOazar8", durationSeconds: 571 },
        { title: "Veena Sahasrabuddhe - Bhajans and Raga Bhairavi", id: "o0G81QHxFPU", durationSeconds: 1598 },
        { title: "Veena Sahasrabuddhe - Bhajans and Raga Bhairavi", id: "xRWijIakvQ0", durationSeconds: 1807 },
        { title: "Veena Sahasrabuddhe - Chhota Khayal in Raga Jaijaiwanti", id: "3i97Vmpe0bA", durationSeconds: 540 },
        { title: "Veena Sahasrabuddhe - Raga Madhmad Sarang", id: "6esaOAIRG2w", durationSeconds: 343 },
      ],
    },
    {
      start: "21:00",
      end: "22:00",
      label: "Health / Finance",
      videos: [
        { title: "The Dark Reality of World's Fattest Country", id: "kk8Z4XIT4Qs", durationSeconds: 1332 },
        { title: "What is Communism?", id: "4UJM4RFQjpU", durationSeconds: 1197 },
        { title: "What is Capitalism?", id: "Cf4uQg03jYg", durationSeconds: 1005 },
        { title: "Sleep Is Your Superpower | Matt Walker | TED", id: "5MuIMqhT8DM", durationSeconds: 1158 },
        { title: "Why Social Health Is Key to Happiness and Longevity | TED", id: "LpSDuDIaBGk", durationSeconds: 576 },
        { title: "The Fundamentals: Why is Investing Important? | The Plain Bagel", id: "I81xqr8HzBE", durationSeconds: 545 },
        { title: "The Difference Between Trading and Investing | The Plain Bagel", id: "dmqoqVwFopE", durationSeconds: 629 },
        { title: "Bonds vs. stocks | Khan Academy", id: "rs1md3e4aYU", durationSeconds: 561 },
        { title: "How stress affects your body - Sharon Horesh Bergquist", id: "v-t1Z5-oPtU", durationSeconds: 282 },
        { title: "How sugar affects the brain - Nicole Avena", id: "lEXBxijQREo", durationSeconds: 303 },
        { title: "How the food you eat affects your brain - Mia Nacamulli", id: "xyQY8a-ng6g", durationSeconds: 292 },
        { title: "What would happen if you didn't sleep? - Claudia Aguirre", id: "dqONk48l5vY", durationSeconds: 275 },
        { title: "How does caffeine keep us awake? - Hanan Qasim", id: "foLf5Bi9qXs", durationSeconds: 315 },
        { title: "Why sitting is bad for you - Murat Dalkilinc", id: "wUEl8KrMz14", durationSeconds: 305 },
        { title: "How does your immune system work? - Emma Bryce", id: "PSRJfaAYkW4", durationSeconds: 323 },
        { title: "What causes headaches? - Dan Kwartler", id: "KpHP8VmxnBo", durationSeconds: 331 },
        { title: "What causes panic attacks, and how can you prevent them? - Cindy J. Aaronson", id: "IzFObkVRSV0", durationSeconds: 323 },
        { title: "The benefits of good posture - Murat Dalkilinc", id: "OyK0oE5rwFY", durationSeconds: 267 },
        { title: "How does the stock market work? - Oliver Elfenbaum", id: "p7HKvqRI_Bo", durationSeconds: 270 },
        { title: "What gives a dollar bill its value? - Doug Levinson", id: "XNu5ppFZbHo", durationSeconds: 231 },
        { title: "Why can't governments print unlimited money? - Jonathan Smith", id: "GFTKKyYSCKs", durationSeconds: 295 },
        { title: "What causes an economic recession? - Richard Coffin", id: "SwaCg7Gwtzw", durationSeconds: 304 },
        { title: "How to spot a misleading graph - Lea Gaslowitz", id: "E91bGT9BjYk", durationSeconds: 250 },
        { title: "Mutual Fund/ETF Keywords & What They Mean | The Plain Bagel", id: "HghsQN89w9k", durationSeconds: 572 },
        { title: "Stock Indices & Index Fund Investing | The Plain Bagel", id: "5A4lp_oZ5zg", durationSeconds: 511 },
        { title: "Bonds | Using Debt to Invest | The Plain Bagel", id: "V-fg5phkl1g", durationSeconds: 425 },
        { title: "Waiting to Invest is Costing You... A Lot | The Plain Bagel", id: "4gn4F1VmTvM", durationSeconds: 769 },
        { title: "What Goes Into Your Credit Score? | Two Cents", id: "ozbGWLtZdoY", durationSeconds: 294 },
      ],
    },
    {
      start: "22:00",
      end: "23:00",
      label: "Short film",
      videos: [
        { title: "Out Full SparkShort | Pixar", id: "OkLZN0ziLuI", durationSeconds: 633 },
        { title: "AFTER THE RAIN | Omeleto", id: "qEaoaRpRRzo", durationSeconds: 535 },
        { title: "1500 WORDS | Omeleto", id: "-waMtGtxAdg", durationSeconds: 526 },
        { title: "LOST AND FOUND | Omeleto", id: "VBps1IvCyj0", durationSeconds: 450 },
        { title: "EXIT STRATEGY | Omeleto", id: "68f27rqP_NY", durationSeconds: 909 },
        { title: "Panthar Mangsho | Ullas Mallick | Mirchi Bangla Audio Story", id: "w9esPNhfPhc", durationSeconds: 2174 },
        { title: "Inhaler | Koustav Samanta | Mirchi Bangla Audio Story", id: "J6MI6QknKGo", durationSeconds: 2012 },
        { title: "Satyajit Ray | Golpokothon by Kollol", id: "zMmaqJERNTY", durationSeconds: 2631 },
        { title: "The New Catacomb | Sir Arthur Conan Doyle | Radio Milan Audio Story", id: "PeIeBt_4IJI", durationSeconds: 1939 },
        { title: "Otithi | Rabindranath Tagore | Radio Milan Audio Story", id: "4VFp3jZk-XM", durationSeconds: 3344 },
        { title: "Hair Love | Sony Pictures Animation", id: "kNw8V_Fkw28", durationSeconds: 408 },
        { title: "The Present | Filmakademie Baden-Wurttemberg", id: "3XA0bB79oGc", durationSeconds: 259 },
        { title: "WiNDUP | Unity", id: "efGqe1j3RNk", durationSeconds: 595 },
        { title: "Alike | Daniel Martinez Lara and Rafa Cano Mendez", id: "PDHIyrfMl_U", durationSeconds: 481 },
        { title: "The Maker | Zealous Creative", id: "YDXOioU_OKM", durationSeconds: 330 },
        { title: "Coin Operated | Animated Short Film", id: "5L4DQfVIcdg", durationSeconds: 315 },
        { title: "One Small Step | TAIKO Studios", id: "yYcpRSQ-irs", durationSeconds: 460 },
        { title: "Snack Attack | Animated Short Film", id: "38y_1EWIE9I", durationSeconds: 281 },
        { title: "In a Heartbeat | Animated Short Film", id: "2REkk9SCRn0", durationSeconds: 246 },
        { title: "Taking Flight | Radio Flyer", id: "Gj6V-xZgtlQ", durationSeconds: 320 },
        { title: "Pip | Short Animated Film", id: "07d2dXHYb94", durationSeconds: 245 },
        { title: "Spring | Blender Open Movie", id: "WhWc3b3KhnY", durationSeconds: 464 },
        { title: "Big Buck Bunny | Blender Open Movie", id: "aqz-KE-bpKQ", durationSeconds: 635 },
        { title: "Sintel | Blender Open Movie", id: "eRsGyueVLvQ", durationSeconds: 888 },
        { title: "The OceanMaker | DUST", id: "uWCGK4nneeU", durationSeconds: 569 },
        { title: "FTL | DUST", id: "t8LD0iUYv80", durationSeconds: 883 },
        { title: "The Door | Screen Ireland", id: "Qn99F3X_LDQ", durationSeconds: 1010 },
        { title: "Curfew | Oscar Winning Short Film", id: "9pq-ua1tGKY", durationSeconds: 1185 },
        { title: "Sing (Mindenki) | KIS KIS", id: "0piiNk_jMrE", durationSeconds: 1499 },
        { title: "The Silent Child | Oscar Winning Short Film", id: "2GbxFIVQv8c", durationSeconds: 1204 },
      ],
    },
    {
      start: "23:00",
      end: "01:00",
      label: "Historical biography / speeches / audiobooks",
      videos: [
        { title: "Rabindranath Tagore - A Film by Satyajit Ray", id: "-VsiBNepmp0", durationSeconds: 3085 },
        { title: "Rabindranath Tagore's Own Voice & Video Footage", id: "EMN8_7C3lzc", durationSeconds: 369 },
        { title: "Sarojini Naidu Greeting Americans In 1928", id: "BlsZvuNhp4U", durationSeconds: 109 },
        { title: "Raja Ram Mohan Roy - The First Indian Liberal", id: "5HTK6XnX-ns", durationSeconds: 946 },
        { title: "How Hitler Brainwashed Millions of People", id: "laisVDBJ204", durationSeconds: 959 },
        { title: "Swami Vivekananda - How Naren became a Monk", id: "PA80BSo8XQQ", durationSeconds: 951 },
        { title: "Rabindranath Tagore - How a School Drop-Out Won the Nobel Prize", id: "HnpMTINOBHo", durationSeconds: 740 },
        { title: "Gandhi in 5 Minutes | British Pathe", id: "codWemzsW40", durationSeconds: 279 },
        { title: "The vision and philosophy of Gandhi | Prasar Bharati Archives", id: "0Etsy3LPddU", durationSeconds: 1713 },
        { title: "1963 - A Talk on Swami Vivekananda | Prasar Bharati Archives", id: "2indUgqt-KU", durationSeconds: 796 },
        { title: "Autobiography of a Yogi, Part 1/3 | LibriVox", id: "hbWzFlszaKM", durationSeconds: 25473 },
      ],
    },
  ],
};
